import MovieGraph from './controller/MovieGraph';

const movies = [
    {
        name: 'Crouching Tiger, Hidden Dragon',
        year: 2000,
        producer: 'Ang Lee',
        rating: 5,
        mpaa_rating: 'PG13',
        runtime: 120,
        theme: ['Star-Crossed Lovers', 'Heroic Mission', 'Opposites Attract'],
        genre: ['Adventure', 'Action', 'Romance', 'Martial Arts', 'Romantic Adventure', 'Period Film'],
        actors: [
            'Chow Yun-Fat',
            'Michelle Yeoh',
            'Ziyi Zhang',
            'Chen Chang',
            'Sihung Lung',
            'Hai Yan',
            'Wang Deming',
            'Huang Su Ying',
            'Zhang Jin Ting',
            'Feng Jian Hua',
        ],
        budget: 15000000,
        country: ['China', 'Hong Kong', 'United States', 'Taiwan'],
    },
    {
        name: 'The Revenant',
        year: 2015,
        producer: 'Alejandro Gonzalez Inarritu, Manny Palo',
        rating: 5,
        mpaa_rating: 'R',
        runtime: 156,
        theme: ['Out For Revenge', 'Survival in the Wilderness', 'When Animals Attack', 'White People Among Indians'],
        genre: ['Action', 'Drama', 'Adventure'],
        actors: [
            'Leonardo DiCaprio',
            'Tom Hardy',
            'Domhnall Gkeeson',
            'Will Poulter',
            'Forrest Goodluck',
            'Paul Anderson',
            'Brad Carter',
            'Bredan Fletcher',
            'Kristofer Joner',
            'Kory Grim',
        ],
        budget: 135000000,
        country: ['United States', 'Canada', 'Philippines'],
    },
    {
        name: 'The Dark Knight',
        year: 2008,
        producer: 'Christopher Nolan',
        rating: 4.5,
        mpaa_rating: 'PG13',
        runtime: 152,
        theme: ['Disfigured Criminals', 'Police Corruption', 'Heroic Mission', 'Double Life'],
        genre: ['Action', 'Crime', 'Crime Drama', 'Superhero Film'],
        actors: [
            'Christian Bale',
            'Heath Ledger',
            'Aaron Eckhart',
            'Maggie Gyllenhaal',
            'Gary Oldman',
            'Morgan Freeman',
            'Micheal Caine',
            'Monique Curmen',
            'Nestor Carbonell',
            'Ron Dean',
        ],
        budget: 180000000,
        country: ['United States'],
    },
    {
        name: 'Emmanuelle',
        year: 1974,
        producer: 'Just Jaeckin',
        rating: 3,
        mpaa_rating: 'R',
        runtime: 94,
        theme: ['Infidelity', 'Sexual Awakening'],
        genre: ['Adult', 'Softcore Sex Film', 'Sexploitation'],
        actors: ['Marika Green', 'Christine Boisson'],
        budget: 500000,
        country: ['France'],
    },
    {
        name: 'Score',
        year: 1973,
        producer: 'Radley Metzger',
        rating: 4,
        mpaa_rating: 'NR',
        runtime: 89,
        theme: ['Infidelity'],
        genre: ['Adult', 'Softcore Sex Film', 'Sexploitation', 'Psychological Drama'],
        actors: ['Claire Wilbur', 'Calvin Culver', 'Gerald Grant', 'Lynn Lowry', 'Carl Parker'],
        budget: 5500000,
        country: ['United States'],
    },
    {
        name: 'Immoral Tales',
        year: 1974,
        producer: 'Walerian Borowczyk',
        rating: 3,
        mpaa_rating: 'Not Rated',
        runtime: 105,
        theme: ['Bohemian Life', 'Rape and Sexual Abuse', 'Sexual Awakening'],
        genre: ['Adult', 'Softcore Sex Film', 'Erituc Drama', 'Avant-grade/Experimental', 'Drama'],
        actors: [
            'Lise Danvers',
            'Fabrice Luchini',
            'Charlotter Alexandra',
            'Paloma Picasso',
            'Florence Bellamy',
            'Pascale Christophe',
        ],
        budget: 700000,
        country: ['France'],
    },
    {
        name: 'Tom Jones',
        year: 1963,
        producer: 'Tony Richardson',
        rating: 5,
        mpaa_rating: 'NR',
        runtime: 160,
        theme: ['Orphans', 'Rags to Riches', 'First Love'],
        genre: ['Adventure', 'Comedy', 'Comedy of Manners', 'Costume Adventure'],
        actors: [
            'Albert Finney',
            'Susannah York',
            'Hugh Griffith',
            'Edith Evans',
            'Joan Greenwood',
            'Diane Cilento',
            'George Devine',
            'David Tomlinson',
            'Joyce Redman',
            'George A. Cooper',
        ],
        budget: 1000000,
        country: ['United Kingdom'],
    },
    {
        name: 'The Treasure of the Sierra Madre',
        year: 1948,
        producer: 'John Huston',
        rating: 5,
        mpaa_rating: 'NR',
        runtime: 126,
        theme: ['Down on Their Luck', 'Treasure Hunts', 'Faltering Friendships', 'Cons and Scams'],
        genre: ['Action', 'Adventure', 'Drama', 'Adventure Drama'],
        actors: [
            'Humphrey Bogart',
            'Tim Holt',
            'Walter Huston',
            'Alfronso Bedoya',
            'Bruce Bennett',
            'Barton MacLane',
            'Arturo Soto Rangel',
            'Manuel Donde',
            'Jose Torvay',
            'Margarito Luna',
        ],
        budget: 3800000,
        country: ['United States', 'Mexico'],
    },
    {
        name: 'King Kong',
        year: 2005,
        producer: 'Peter Jackson',
        rating: 4,
        mpaa_rating: 'PG13',
        runtime: 187,
        theme: ['Monkeys', 'Lost Worlds', 'Woman In Jeopardy', 'Filmmaking'],
        genre: ['Adventure', 'Creature Film', 'Period Film', 'Jungle Film'],
        actors: [
            'Naomi Watts',
            'Jack Black',
            'Adrien Brody',
            'Thomas Kretschmann',
            'Colin Hanks',
            'Jamie Bell',
            'Lobo Chan',
            'Evan Parke',
            'John Sumner',
            'Craig Hall',
        ],
        budget: 207000000,
        country: ['United States', 'Germany', 'New Zealand'],
    },
    {
        name: 'The Adventure of Robin Hood',
        year: 1938,
        producer: 'Michael Curtiz / William Keighley',
        rating: 5,
        mpaa_rating: 'NR',
        runtime: 102,
        theme: ['Righting the Wronged', 'Daring Rescues', 'Heroic Mission', 'Opposites Attract'],
        genre: ['Adventure', 'Swashbuckler', 'Costume Adventure', 'Romantic Adventure'],
        actors: [
            'Errol Flynn',
            'Olivia de Havilland',
            'Basil Rathbone',
            'Claude Rains',
            'Eugene Pallette',
            'Alan hale',
            "Una O'connor",
            'Patric Knowles',
            'Melville Cooper',
            'Herbert Mundin',
        ],
        budget: 2000000,
        country: ['United States'],
    },
];

function App() {
    let mg = new MovieGraph(movies);
    console.log(mg.matrix);

    return <div className="App"></div>;
}

export default App;
